spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://158.160.59.159:5555/test
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
server:
  port: 8080
jwt:
  secret:
    key: asdjkmasdmkaskdmaskmd

springdoc:
  swagger-ui:
    path: /docs

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: artem.kuryshkin@gmail.com
  password: ovyuoiivpygyiykn
  properties.mail.smtp:
    auth: true
    starttls.enable: true
    ssl.trust: smtp.gmail.com