create table person(
                       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(30) NOT NULL,
                       surname varchar(30) NOT NULL,
                       year_of_birth int NOT NULL,
                       country varchar(25) NOT NULL,
                       activation_code varchar(36) UNIQUE,
                       email varchar(50) NOT NULL UNIQUE,
                       password varchar(60) NOT NULL,
                       role varchar(20) NOT NULL,
                       created_at timestamp NOT NULL,
                       updated_at timestamp NOT NULL
);

create table refresh_token(
                              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              person_id int REFERENCES person(id) ON DELETE CASCADE NOT NULL UNIQUE
);

create table product(
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(30) NOT NULL,
                        cost int NOT NULL,
                        description varchar(400) NOT NULL,
                        created_at timestamp NOT NULL,
                        updated_at timestamp NOT NULL,
                        battery_capacity smallint NOT NULL,
                        power smallint NOT NULL,
                        speed smallint NOT NULL,
                        time smallint NOT NULL
);

create table image(
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      product_id bigint REFERENCES product(id) ON DELETE CASCADE NOT NULL,
                      content_type smallint NOT NULL,
                      original_file_name varchar(36) NOT NULL,
                      created_at timestamp NOT NULL
);

create table comment(
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        product_id bigint REFERENCES product(id) ON DELETE CASCADE NOT NULL,
                        person_id bigint REFERENCES person(id) ON DELETE CASCADE NOT NULL,
                        mark smallint NOT NULL,
                        text varchar(400) NOT NULL,
                        created_at timestamp NOT NULL,
                        updated_at timestamp NOT NULL
);

create table cart(
                     id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     product_id bigint REFERENCES product(id) ON DELETE CASCADE NOT NULL,
                     amount bigint NOT NULL,
                     person_id bigint REFERENCES person(id) ON DELETE CASCADE NOT NULL
);

create table restore_password
(
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token     varchar(36) NOT NULL UNIQUE,
    person_id bigint REFERENCES person (id) ON DELETE CASCADE NOT NULL,
    created_at timestamp NOT NULL
)

create table avatar(
                       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       person_id bigint references person(ID) on delete cascade,
                       original_file_name varchar(36) NOT NULL,
                       content_type smallint NOT NULL,
                       created_at timestamp NOT NULL
)

SELECT cron.schedule('0 10 * * *’, $$DELETE FROM restore_password WHERE created_at < now() - interval '1 days’$$);